repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_validate
      #- id: terraform_tflint
        # args:
        #   - >
        #     --args=--minimum-severity HIGH
        #     --include-ignored
      - id: terraform_providers_lock
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.14.0"
    hooks:
      - id: check-github-actions
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "2.1.6"
    hooks:
      - id: shellcheck
        args: [--severity=error]
